### ISSUE TITLE
Unable to install PSP font and new shaders

### ISSUE THREAD

**Issue by ObmijSelaw** [Nightmayr-snaps/ppsspp-snap#2]
What the title says. I'm using PPSSPP v1.11. I'm trying to install the original PSP fonts for this emulator to solve problems with the fonts of some games (as indicated by this [guide:](https://cdromance.com/guides/original-psp-fonts-for-ppsspp-for-android-and-pc-download/) However, the "assets" folder is not editable by the user as it's mounted as part of the snap, making it impossible to follow this guide. Since the shaders are also located in this folder, it's also impossible to install new shaders (without creating a new snap).

I'll share information about my system:
OS: KDE neon User Edition 5.21 x86_64
Kernel: (Linux) 5.4.0-70-generic
CPU: Intel i7-4600U (4) @ 3.300GHz 
GPU: Intel Haswell-ULT

(Edited to fix URL)

**Comment by Nightmayr** [comment]
I think this might be something I can't do much about. The problem being as you mentioned the the assets folder being non editable by the user and requiring the fonts to be bundled as part of the snap. I don't think I'd be able to distribute these fonts due to being copyright protected. I'll raise this over on the snapcraft forums but I suspect there will currently be no solution as the non editable snap directory is by design for security.

**Comment by ObmijSelaw** [comment]
I see, I guess things like this might be one of the reasons why some people don't like snaps. In any case, the problem with the fonts is mostly on PPSSPP devs side because their fonts are bugged on a few games. Thanks for your reply.
